# Site settings
title: "Annette Ibarra"
description: "A resume website for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Annette Ibarra"
resume_title:                   "Developer & UX/UI Designer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "annie.livinlife11@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "858-344-9587"
resume_contact_address:         "Escondido, CA"

resume_header_contact_info:     "Escondido, CA • 858-344-9587 • annie.livinlife11@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>A self-motivated, creative programmer-turned UX designer with a passion for analytics and the ability to learn quickly. My global training in Computer Science and Mathematics, along with years of collaboration with designers, marketers, and software engineers, offers a holistic approach to design and development. I am eager to work in a team of passionate and fastidious professionals in Developer/UX Design positions. Aiming to find a professional position to both advance and contribute skills as a developer and designer.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/annieibarra"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/annetteibarra/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "/Untitled003.pdf"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_pdf_url:                 "/pdfs/Jan2019_Resume.pdf"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
